### ISSUE TITLE
[Feature Request] Env vars configuration (for heroku and docker)

### ISSUE THREAD

**Issue by JuniorJPDJ** [emptycodes/AllegroRSS#1]
It would be nice to see env vars overriding config vars, so we can make it a good container and deploy on some cloud ;D

**Comment by emptycodes** [comment]
Last added commit https://github.com/emptycodes/AllegroRSS/commit/529ba7b20aef349c54cceeaea850eddbd4ae67c5 giving possibility using env vars for add configs parameters. I'll give more support for Heroku and Docker in next time! ^^
